- name: Upload coverage reports to Codecov
  on:
    push:
      # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-excluding-paths
      paths-ignore:
        - 'docs/**'
        - '**.md'
    pull_request:
      paths-ignore:
        - 'docs/**'
        - '**.md'

  uses: codecov/codecov-action@v4.0.1
  with:
    token: ${{ secrets.CODECOV_TOKEN }}
    slug: joker-pper/hierarchy-utils